name: PR-CI

on:
  pull_request:
    branches: [ develop, v1.x-develop ]

env:
  DOCKER_REPO: wuyfeedocker/nacos-ci
  REPO_NAME: Wuyunfan-BUPT/nacos
  HEADER_PARAMS: "-H \"Accept: application/vnd.github+json\" -H \"Authorization: Bearer ${{ secrets.ACTION_TOKEN }}\" -H \"X-GitHub-Api-Version: 2022-11-28\""
  BASE_URL: https://api.github.com/repos/Wuyunfan-BUPT/nacos/actions/variables

jobs:
  dist-tar:
    name: Build distribution tar
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
          cache: "maven"
      - name: Build distribution tar
        run: |
          mvn -Prelease-nacos -DskipTests clean install -U -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - uses: actions/upload-artifact@v3
        name: Upload distribution tar
        with:
          name: nacos
          path: distribution/target/nacos-server-*.tar.gz
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
      - name: generate temp variables
        run: |
          echo VAR_${{ github.run_id }}: ${{ github.event.pull_request.number }}
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$GITHUB_REPOSITORY/actions/variables -d "{\"name\":\"VAR_${{ github.run_id }}\",\"value\":\"${{ github.event.pull_request.number }}\"}"
